# Generated by Django 5.0.1 on 2024-01-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=1, upload_to='employees'),
            preserve_default=False,
        ),
    ]
