# Generated by Django 5.0.1 on 2024-03-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth',
            field=models.CharField(max_length=10),
        ),
    ]
