# Generated by Django 5.0.1 on 2024-01-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='image',
            field=models.ImageField(default=1, upload_to='units'),
            preserve_default=False,
        ),
    ]
