# Generated by Django 5.0.1 on 2024-03-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_unit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='active',
            field=models.CharField(max_length=5),
        ),
    ]
