# Generated by Django 5.0.1 on 2024-01-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
