# Generated by Django 5.0.1 on 2024-01-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, upload_to='cars/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
