# Generated by Django 5.0.1 on 2024-01-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_image_delete_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('blue', 'Blue'), ('red', 'Red'), ('yellow', 'Yellow'), ('brown', 'Brown'), ('black', 'Black'), ('gray', 'Gray'), ('purple', 'Purple'), ('green', 'Green')], max_length=200),
        ),
    ]
